spring:
  application:
    name: rabbitmq-example-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtual-host: root-vhost
    publisher-returns: true
    publisher-confirm-type: simple
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
server:
  port: 8890
